language: cpp

os:
    - linux

matrix:
    include:
        - compiler: gcc
          env: COMPILER_CC=gcc-4.8 COMPILER_CXX=g++-4.8     STD=c++11 BUILD_TYPE=Debug
        - compiler: gcc
          env: COMPILER_CC=gcc-4.8 COMPILER_CXX=g++-4.8     STD=c++11 BUILD_TYPE=Release

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -yqq

install:
    - sudo apt-get install -yqq gcc-4.8 g++-4.8

before_script:
    - cmake -H. -Bout -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_C_COMPILER=${COMPILER_CC} -DCMAKE_CXX_COMPILER=${COMPILER_CXX} -DCMAKE_CXX_FLAGS="-std=${STD}"

script:
    - make -C out
    - out/test/unit_tests
    - if [ "$BUILD_TYPE" == "Release" ]; then out/bench/benchmarks; fi

notifications:
    email:
        recipients:
            - utatane.tea@gmail.com
        on_success: change
        on_failure: always
