language: cpp

compiler:
    - clang
    - gcc-4.8

os:
    - linux

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -yqq

install:
    - sudo apt-get install -yqq libc6-dev gnulib gcc-4.8 g++-4.8

before_script:
    - "cmake -H. -Bout -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX"

script:
    - make -C out
    - out/test/unit_tests
    - if [ "$BUILD_TYPE" == "Release" ]; then out/bench/benchmarks; fi

notifications:
    email:
        recipients:
            - utatane.tea@gmail.com
        on_success: change
        on_failure: always
